/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import Business.Veteran.Veteran;
import Business.Veteran.VeteranDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author dgoda
 */
public class RegisterVeteran extends javax.swing.JPanel {

    VeteranDirectory vet_Dir;
    UserAccountDirectory user_Dir;
    /**
     * Creates new form RegisterVeteran
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private Employee emp;

    public RegisterVeteran(JPanel userProcessContainer, EcoSystem system, VeteranDirectory vet_Dir, UserAccountDirectory user_Dir) {
        initComponents();
        this.vet_Dir = vet_Dir;
        this.user_Dir = user_Dir;
        this.userProcessContainer = userProcessContainer;
        this.system = system;

        String f = "img/goArmy.jpg";
        ImageIcon ficon = new ImageIcon(f.toString());
        Image fimage = ficon.getImage();
        Image fimagescaling = fimage.getScaledInstance(300, 75, Image.SCALE_SMOOTH);
        ImageIcon scaled = new ImageIcon(fimagescaling);
        pictureArea1.setIcon(scaled);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtResAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtArmyType = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEducationDetails = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtVeteranID = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pictureArea1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_CurrentConcern = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_CriticalityLevel = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_CoordX = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_CoordY = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 204));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("First Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 220, -1));

        jLabel3.setText("Last Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 220, -1));

        jLabel4.setText("Address");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 60, 20));
        add(txtResAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 220, -1));

        jLabel5.setText("Military Branch");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, 20));

        txtArmyType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArmyTypeActionPerformed(evt);
            }
        });
        add(txtArmyType, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 220, -1));

        jLabel6.setText("Age");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, 20));
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 220, -1));

        jLabel7.setText("Gender");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));

        jLabel8.setText("Education Details");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        txtEducationDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEducationDetailsActionPerformed(evt);
            }
        });
        add(txtEducationDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 220, -1));

        jButton1.setBackground(new java.awt.Color(20, 53, 94));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Register Troop");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 630, 380, -1));

        jLabel9.setText("Troop ID");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, -1));

        txtVeteranID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVeteranIDActionPerformed(evt);
            }
        });
        add(txtVeteranID, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 220, -1));

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 220, -1));

        jLabel10.setText("User Name");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, -1, -1));

        jLabel11.setText("Password");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, -1, 30));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel12.setText("Concerns");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 300, -1));

        jLabel13.setText("Enter all troop details");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel15.setText("Provide Credentials");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 200, -1));
        add(pictureArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 340, 70));

        jLabel14.setText("State the Current Concern");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 160, 20));
        add(txt_CurrentConcern, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, 190, -1));

        jLabel16.setText("Criticality Level");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 160, 20));
        add(txt_CriticalityLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 190, -1));

        jLabel17.setText("Co-ord X");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 160, 20));
        add(txt_CoordX, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, 190, -1));

        jLabel18.setText("Co-ord Y");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 160, 20));
        add(txt_CoordY, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 370, 190, -1));

        jLabel19.setText("Please help us to serve you better.Please enter the possible co-ordinates");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 370, 20));

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel20.setText("Register a Troop");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 300, -1));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 580, 220, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Prefer not to Answer" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 220, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtEducationDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEducationDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEducationDetailsActionPerformed

    private void txtArmyTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArmyTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArmyTypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        char[] passwordCharArray = jPasswordField1.getPassword();
        String password = String.valueOf(passwordCharArray);
        if (txtFirstName.getText().equals("")) {
            JOptionPane.showMessageDialog(null, " First Name can't be empty");
            return;
        }
        if (txtLastName.getText().equals("")) {
            JOptionPane.showMessageDialog(null, " Last Name can't be empty");
            return;
        }
        if (txtUsername.getText().equals("")) {
            JOptionPane.showMessageDialog(null, " User Name can't be empty");
            return;
        }
        if (password.equals("")) {
            JOptionPane.showMessageDialog(null, " Password can't be empty");
            return;
        }
        try {
            if (!txtAge.getText().equals("")) {
                Integer.parseInt(txtAge.getText());
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Age cannot be String");
            return;
        }
        try {
            if (!txt_CoordX.getText().equals("")) {
                Double.parseDouble(txt_CoordX.getText());
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Coord X cannot be String");
            return;
        }
        try {
            if (!txt_CoordY.getText().equals("")) {
                Double.parseDouble(txt_CoordY.getText());
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, " Coord Y cannot be String");
            return;
        }

        Veteran v = system.getVd().addVeteran();
        system.getUad().createUserAccount(txtUsername.getText(), password);
        v.setFirstName(txtFirstName.getText());
        v.setLastName(txtLastName.getText());
        v.setAge(txtAge.getText());
        v.setArmyType(txtArmyType.getText());
        v.setVeteran_ID(txtEducationDetails.getText());
        v.setGender((String) jComboBox1.getSelectedItem());
        v.setResidentAddress(txtResAddress.getText());
        v.setArmyType(txtArmyType.getText());
        v.setVeteran_ID(txtVeteranID.getText());
        v.setUsername(txtUsername.getText());
        v.setPassword(password);
        v.setCurrentConcern(txt_CurrentConcern.getText());
        v.setCriticalityLevel(txt_CriticalityLevel.getText());
        v.setCoordX(txt_CoordX.getText());
        v.setCoordY(txt_CoordY.getText());
        System.out.println("Registered veteran succesfully");
        txtFirstName.setText("");
        txtLastName.setText("");
        txtAge.setText("");
        txtArmyType.setText("");

        txtEducationDetails.setText("");
        txtArmyType.setText("");
        txtResAddress.setText("");
        txtVeteranID.setText("");
        txt_CoordX.setText("");
        txt_CoordY.setText("");
        txt_CurrentConcern.setText("");
        txt_CriticalityLevel.setText("");
//        
//        String userName = txtUsername.getText();
//        String password = txtPassword.getText();

        txtUsername.setText("");
        jPasswordField1.setText("");
//        Organization organization = (Organization) Type.Veteran;

//        Organization organization = (Organization) jComboBox1.getSelectedItem();
//        Employee employee = (Employee) employeeJComboBox.getSelectedItem();
//        Role role = (Role) Veteran;
//        Employee employee = enterprise.getEmployeeDirectory().createEmployee(txtFirstName);
//        organization.getUserAccountDirectory().createUserAccount(userName, password);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtVeteranIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVeteranIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVeteranIDActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel pictureArea1;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtArmyType;
    private javax.swing.JTextField txtEducationDetails;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtResAddress;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtVeteranID;
    private javax.swing.JTextField txt_CoordX;
    private javax.swing.JTextField txt_CoordY;
    private javax.swing.JTextField txt_CriticalityLevel;
    private javax.swing.JTextField txt_CurrentConcern;
    // End of variables declaration//GEN-END:variables
}
