/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Veteran.Veteran;
import javax.swing.table.DefaultTableModel;
import Business.Veteran.VeteranDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author dgoda
 */
public class ViewAllVeterans extends javax.swing.JPanel {
   private JPanel userProcessContainer;
    private EcoSystem system;
    VeteranDirectory vet_Dir;
    /**
     * Creates new form ViewAllVeterans
     */
    public ViewAllVeterans(JPanel userProcessContainer, EcoSystem system,VeteranDirectory vet_Dir) {
        initComponents();
        this.vet_Dir = vet_Dir;
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateVeteranDetails();
    }
 public void populateVeteranDetails() {
        int rowCount = tblViewAllVeteran.getRowCount();
        DefaultTableModel model = (DefaultTableModel) tblViewAllVeteran.getModel();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }

        for (Veteran v : system.getVd().getVeteran_Dir()) {
            Object row[] = new Object[6];
            row[0] = v;
            row[1] = v.getVeteran_ID();
            row[2] = v.getAge();
            row[3]= v.getGender();
            row[4]= v.getCurrentConcern();
            row[5]=v.getCriticalityLevel();
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewAllVeteran = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblViewAllVeteran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Troop Name ", "Troop ID", "Age", "Gender", "Current Concern", "Criticality level"
            }
        ));
        jScrollPane1.setViewportView(tblViewAllVeteran);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 820, 185));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("View  and track Troops");
        jLabel6.setFocusable(false);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 50, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 51));
        jButton1.setText("Track Troop");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 140, 30));
    }// </editor-fold>//GEN-END:initComponents

     
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblViewAllVeteran.getSelectedRow();

        if (selectedRow >= 0) {
            Veteran v = (Veteran) tblViewAllVeteran.getValueAt(selectedRow, 0);
             String coordX = v.getCoordX();
              String coordY = v.getCoordY();
         JFrame test = new JFrame("Google Maps");

        try {
            String imageUrl = "https://maps.googleapis.com/maps/api/staticmap?center="+coordX+","+ coordY +"&markers=color:red%7Clabel:G%7C40.711614,-74.012318&zoom=16&size=600x300&key=AIzaSyACgsl2TkE6C_oKz9SwJdnCZCKLbss2fyI";
            String destinationFile = "image.jpg";
            String str = destinationFile;
            URL url = new URL(imageUrl);
            InputStream is = url.openStream();
            OutputStream os = new FileOutputStream(destinationFile);

            byte[] b = new byte[2048];
            int length;

            while ((length = is.read(b)) != -1) {
                os.write(b, 0, length);
            }

            is.close();
            os.close();
        } catch (IOException e) {
            e.printStackTrace();
            System.exit(1);
        }

        test.add(new JLabel(new ImageIcon((new ImageIcon("image.jpg")).getImage().getScaledInstance(630, 600,
            java.awt.Image.SCALE_SMOOTH))));

test.setVisible(true);
test.pack();
        }
        else{
            JOptionPane.showMessageDialog(null,"Please select any row from the above table","Warning",JOptionPane.WARNING_MESSAGE);
        }
        
       
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblViewAllVeteran;
    // End of variables declaration//GEN-END:variables
}
